In [1]:
import numpy as np
import sympy as sp

x1 = sp.Symbol("x1")
x2 = sp.Symbol("x2")
a = sp.Symbol("a")

f = 1/2*(x1**2 + 2*x2**2) - (x1 - x2) + 7
nilai_awal = [0,0]
h = np.identity(2)
error = 10**-6

def quasi_newton(f):
    print("f'(x) =")
    ft = np.array([f.diff(x1),f.diff(x2)]).reshape(2,-1)
    print(ft)
    
    n = 1
    convergent = True
    condition = True
    while condition:
        print("\n----------------Iterasi {}----------------".format(n))
        if n >= 2:
            print("\ndelta x{} =".format(n - 2))
            delta_x = a_lama * d_lama
            print(delta_x)
        
        print("\ng{} =".format(n - 1))
        if n == 1:
            g = np.array([ft[0][0].subs({x1:nilai_awal[0],x2:nilai_awal[1]}),
                          ft[1][0].subs({x1:nilai_awal[0],x2:nilai_awal[1]})]).reshape(2,-1)
            print(g)
        else:
            g = np.array([ft[0][0].subs({x1:x_lama[0][0],x2:x_lama[1][0]}),
                          ft[1][0].subs({x1:x_lama[0][0],x2:x_lama[1][0]})]).reshape(2,-1)
            print(g)
                   
        if n >= 2:
            print("\ndelta g{} =".format(n - 2))
            delta_g = g - g_lama
            print(delta_g)
            
            print("\ndelta x{} - H{}.delta g{} =".format(n - 2,n - 2,n - 2))
            pengurangan = delta_x - np.dot(h,delta_g)
            print(pengurangan)
            
            print("\nH{} =".format(n - 1))
            h_baru = h + np.divide(np.dot(pengurangan,pengurangan.transpose()),np.dot(delta_g.transpose(),pengurangan))
            print(h_baru)

        if n == 1:
            print("\nd{} =".format(n - 1))
            d = np.dot(-1 * h,g)
            print(d)
        else:
            print("\nd{} =".format(n - 1))
            d = np.dot(-1 * h_baru,g)
            print(d)            

        pertama = d.transpose()
        kedua = np.array([ft[0][0].subs({x1:nilai_awal[0] + a*d[0][0],x2:nilai_awal[1] + a*d[1][0]}),
                          ft[1][0].subs({x1:nilai_awal[0] + a*d[0][0],x2:nilai_awal[1] + a*d[1][0]})]).reshape(2,-1)
        hasil = np.dot(pertama,kedua)
        hasil_a = sp.solve(hasil[0][0],a)[0]
        print("\na{} = {}".format(n - 1,hasil_a))

        print("\nx{} =".format(n))
        if n == 1:
            x = np.array(nilai_awal).reshape(2,-1) + hasil_a*d
            print(x)
        else:
            x = np.array(x_lama).reshape(2,-1) + hasil_a*d
            print(x)
        
        if n > 1:
            if (g[0][0] < error) & (g[1][0] < error):
                g = np.array([0,0]).reshape(2,-1)
                print("\ng{} =".format(n))
                print(g)
                print("\nKarena g{} = 0, proses perhitungan dihentikan.".format(n))
                break
            elif np.linalg.det(h_baru) < error:
                print("\nKarena matriks H tidak definit positif, proses perhitungan dihentikan.")
            elif (abs((x_lama - x)[0][0]) < error) & (abs((x_lama - x)[1][0]) < error):
                print("\nabs(x{} - x{}) =".format(n,n-1))
                print(x_lama - x)
                print("\nKarena abs(x{} - x{}) < {}, proses perhitungan dihentikan.".format(n,n-1,error))
                condition = False
        
        if n > 100:
            convergent = False
            break

        x_lama = x
        g_lama = g
        d_lama = d
        a_lama = hasil_a
        n += 1

    nilai_minimum = f.subs({x1:x[0][0],x2:x[1][0]})
    print("\nNilai minimum f adalah {}".format(nilai_minimum))
            
quasi_newton(f)

f'(x) =
[[1.0*x1 - 1]
 [2.0*x2 + 1]]

----------------Iterasi 1----------------

g0 =
[[-1]
 [1]]

d0 =
[[1.00000000000000]
 [-1.00000000000000]]

a0 = 0.666666666666667

x1 =
[[0.666666666666667]
 [-0.666666666666667]]

----------------Iterasi 2----------------

delta x0 =
[[0.666666666666667]
 [-0.666666666666667]]

g1 =
[[-0.333333333333333]
 [-0.333333333333333]]

delta g0 =
[[0.666666666666667]
 [-1.33333333333333]]

delta x0 - H0.delta g0 =
[[0]
 [0.666666666666667]]

H1 =
[[1.00000000000000 0]
 [0 0.500000000000000]]

d1 =
[[0.333333333333333]
 [0.166666666666667]]

a1 = 1.00000000000000

x2 =
[[1.00000000000000]
 [-0.500000000000000]]

g2 =
[[0]
 [0]]

Karena g2 = 0, proses perhitungan dihentikan.

Nilai minimum f adalah 6.25000000000000
